#
# This is free software, lisence use MIT.........................
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt_x86_6.12.x

on:
  push:
    branches:
      - master
  release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: OpenWrt ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [x86]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: 查看机器配置
        run: |
         echo "警告⚠"
         echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
         echo -e "CPU性能排序: 7763 > 8370C > 8272CL > 8171M > E5-2673\n"
         echo "--------------------------CPU信息--------------------------"
         echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
         echo "CPU核心数量: $(nproc)"
         echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
         echo "--------------------------内存信息--------------------------"
         echo "已安装内存详细信息:"
         echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
         echo "--------------------------硬盘信息--------------------------"
         echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Build
        run: |
          echo "Free space:"
          df -h
          date
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          echo "date2=$(date +'%m/%d %Y')" >> $GITHUB_ENV
          echo "date3=$(date +'%m.%d')" >> $GITHUB_ENV
          echo "DOCKERTAG=${{ secrets.DOCKER_ID }}/openwrt-6p:latest" >> $GITHUB_ENV
          VERSION="$(echo "${{github.event.action}}" | grep -Eo " [0-9.]+" | sed -e 's/ //')" || true
          [ "$VERSION" ] && echo "VERSION=$VERSION" >> $GITHUB_ENV || echo "VERSION=$(date +'%m.%d')" >> $GITHUB_ENV
   
      - name: other package
        run: |
          rm -rf package/helloworld
          git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld
          git -C package/helloworld pull
          df -h
          ls -sh
      #- name: Free up disk space
        #run: |
          #sudo mkdir -p -m 777 /mnt/openwrt/dl /mnt/openwrt/bin /mnt/openwrt/staging_dir
          #ln -sf /mnt/openwrt/dl dl
          #ln -sf /mnt/openwrt/bin bin
          #ln -sf /mnt/openwrt/staging_dir staging_dir

          #echo "Symlinks created:"
          #ls -l
          #echo ""
          #echo "Disk usage:"
          #df -h

      - name: Update feeds
        run: |
          # sed -i '1i src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
          sed -i '1i src-git small https://github.com/kenzok8/small' feeds.conf.default
          sed -i '2i src-git vmware https://github.com/vmware/open-vm-tools' feeds.conf.default
          sed -i '3i src-git taskplan https://github.com/sirpdboy/luci-app-taskplan' feeds.conf.default
          # sed -i '5i src-git lucky https://github.com/gdy666/luci-app-lucky' feeds.conf.default
          # sed -i '6i src-git openlist2 https://github.com/sbwml/luci-app-openlist2' feeds.conf.default
          ./scripts/feeds update -a 
          rm -rf feeds/luci/applications/luci-app-mosdns
          rm -rf feeds/packages/net/{alist,openlist,adguardhome,mosdns,xray*,v2ray*,v2ray*,sing*,smartdns}
          rm -rf feeds/packages/utils/v2dat
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cat ./feeds.conf.default
      - name: Get new themes
        run: |
          rm -rf package/feeds/luci/luci-theme-argon
          rm -rf package/feeds/luci/luci-app-argon-config
          rm -rf package/feeds/luci/luci-theme-infinityfreedom
          rm -rf package/feeds/luci/luci/luci-theme-design
          #rm -rf package/feeds/luci/luci-theme-opentopd
          #rm -rf package/feeds/luci/luci-theme-neobird
          git clone -b master https://github.com/jerrykuku/luci-theme-argon.git package/feeds/luci/luci-theme-argon
          git clone -b master https://github.com/jerrykuku/luci-app-argon-config.git package/feeds/luci/luci-app-argon-config
      
      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分========================
          # 
          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_TESTING_KERNEL=n
          EOF
          # 固件大小设置:
          cat >> .config <<EOF
          CONFIG_TARGET_KERNEL_PARTSIZE=128
          CONFIG_TARGET_ROOTFS_PARTSIZE=640
          EOF
          
          # 固件压缩:
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          EOF
          
          # 编译UEFI固件:
          cat >> .config <<EOF
          CONFIG_EFI_IMAGES=y
          EOF
          
          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          EOF
          
          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
         
          EOF
          # bonding支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-bonding=y
          CONFIG_PACKAGE_proto-bonding=y
          CONFIG_PACKAGE_luci-proto-bonding=y
          EOF
          
          # USB3.0支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          EOF
          
          # 常用LuCI插件选择:
          cat >> .config <<EOF
          # CONFIG_PACKAGE_luci-app-adbyby-plus=y
          # CONFIG_PACKAGE_luci-app-aria2=y
          # CONFIG_PACKAGE_luci-app-docker=y
          # CONFIG_PACKAGE_luci-app-frpc=y
          # CONFIG_PACKAGE_luci-app-frps=y
          # CONFIG_PACKAGE_luci-app-uugamebooster=y
          # CONFIG_PACKAGE_luci-app-qbittorrent=y
          # CONFIG_PACKAGE_luci-app-baidupcs-web=y
          # CONFIG_PACKAGE_luci-app-mwan3=y
          # CONFIG_PACKAGE_luci-app-mwan3helper=y
          # CONFIG_PACKAGE_luci-app-airplay2=y
          # CONFIG_PACKAGE_luci-app-transmission=y
          # CONFIG_PACKAGE_luci-app-netdata=y
          # CONFIG_PACKAGE_luci-app-store=y 
          # CONFIG_PACKAGE_luci-app-aliyundrive-webdav=y
          # CONFIG_PACKAGE_luci-app-unblockneteasemusic=y
          # CONFIG_PACKAGE_luci-app-advanced=y
          CONFIG_PACKAGE_luci-app-eqos=y
          # CONFIG_PACKAGE_luci-app-pushbot=y
          # CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-watchcat=y
          CONFIG_PACKAGE_luci-app-cpufreq=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-nfs=y
          # CONFIG_PACKAGE_luci-app-verysync=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-msd_lite=y
          # CONFIG_PACKAGE_luci-app-lucky=y
          CONFIG_PACKAGE_luci-app-filebrowser=n
          # CONFIG_PACKAGE_luci-app-vssr=y
          # CONFIG_PACKAGE_luci-app-v2ray-server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-passwall=n
          CONFIG_PACKAGE_luci-app-passwall2=y 
          CONFIG_PACKAGE_luci-app-openclash=y
          # CONFIG_PACKAGE_luci-app-mihomo=y
          # CONFIG_PACKAGE_luci-app-homeproxy=y
          # CONFIG_PACKAGE_luci-app-adguardhome=y
          # CONFIG_PACKAGE_luci-app-smartdns=y
          # CONFIG_PACKAGE_luci-app-mosdns=y
          # CONFIG_PACKAGE_luci-app-softethervpn=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-openvpn-server=y
          CONFIG_PACKAGE_openvpn-easy-rsa=y
          # CONFIG_PACKAGE_luci-app-zerotier=y
          # CONFIG_SING_BOX_WITH_WIREGUARD=y
          CONFIG_PACKAGE_kmod-wireguard=y
          CONFIG_PACKAGE_luci-proto-wireguard=y          
          CONFIG_PACKAGE_wireguard-tools=y
          CONFIG_PACKAGE_luci-app-taskplan=y
          CONFIG_PACKAGE_luci-app-openlist2=n
          EOF
          
          # LuCI主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-app-argon-config=y
          # CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          # CONFIG_PACKAGE_luci-theme-material=y
          # CONFIG_PACKAGE_luci-theme-opentomato=y
          # CONFIG_PACKAGE_luci-theme-infinityfreedom
          # CONFIG_PACKAGE_luci-theme-opentopd=y
          # CONFIG_PACKAGE_luci-theme-neobird=y
          EOF
          
          # 常用软件包:
          cat >> .config <<EOF
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_tree=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_wget=y
          CONFIG_PACKAGE_acme=y
          CONFIG_PACKAGE_acme-dnsapi=y
          CONFIG_PACKAGE_haproxy=y
          CONFIG_PACKAGE_socat=y
          CONFIG_SOCAT_SSL=y
          CONFIG_SING_BOX_WITH_ECH=n
          CONFIG_PACKAGE_chinadns-gn=y
          CONFIG_PACKAGE_open-vm-tools=y
          CONFIG_PACKAGE_iperf3=y
          CONFIG_PACKAGE_iftop=y
          CONFIG_PACKAGE_tcpdump=y
          CONFIG_PACKAGE_pv=y
          CONFIG_PACKAGE_bind-host=y
          CONFIG_PACKAGE_firewall4=y
          EOF
          
          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          # cat >> .config <<EOF
          # # CONFIG_TARGET_IMAGES_PAD is not set
          # # CONFIG_VMDK_IMAGES is not set
          # EOF
          # 
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
     
      - name: Make download
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: Cache OpenWrt Build
        uses: stupidloud/cachewrtbuild@main
        with:
          ccache: 'true'
          mixkey: ${{ matrix.target }}
          clean: ${{ contains(github.event.action, 'nocache') }}
          prefix: ${{ github.workspace }}
          toolchain: 'true'       
          skip: 'true'
          skip_saving: 'false'

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j16 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
     
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type f -name "openwrt-x86-64-generic-kernel.bin")
          rm -rf $(find ./bin/targets/ -type f -name "openwrt-x86-64-generic-squashfs-rootfs.img.gz")
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
         
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ env.date }}_OpenWrt_x86_buildinfo_6.12.x
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ env.date }}_OpenWrt_x86_package_6.12.x
          path: ./artifact/package/
      
      - name: Deliver firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date }}_OpenWrt_x86_firmware_6.12.x
          path: ./bin/targets/
     
      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.SEARIY_TOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: 'true'

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.SEARIY_TOKEN }}
          retain_days: 20
          keep_minimum_runs: 1
